# Generated by Django 4.0.5 on 2022-06-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/blog/%Y/%m/%d')),
                ('name', models.CharField(max_length=20)),
                ('like', models.IntegerField()),
                ('view', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
